# Generated by Django 5.2.15 on 2026-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="bracket_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="bracket_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
